/**
 *
 * @desc types code
 * @author PDK
 *
 * Created at     : 2019-03-21
 * Last modified  : 2019-03-27
 */
module.exports = {
  global: {
    INVALID_REQUEST: -1,
    UPLOAD_FILE_SUCCESS: 1,
    UPLOAD_FILE_FAIL: -1,
    CREATE_SUCCESS: 1,
    CREATE_FAIL: -1,
    UPDATE_SUCCESS: 1,
    UPDATE_FAIL: -1,
    RETRIEVE_LIST_SUCCESS: 1,
    RETRIEVE_LIST_FAIL: -1,
    DELETE_SUCCESS: 1,
    DELETE_FAIL: -1,
  },
  login: {
    RETRIEVE_EMAIL_CODE_SUCCESS: 1,
    RETRIEVE_EMAIL_CODE_FAIL: -1,
    CHECK_EMAIL_CODE_ERROR: -1,
    CHECK_EMAIL_CODE_SUCCESS: 1,
    LOGIN_SUCCESS: 1,
    LOGIN_FAIL: -1,
    GET_USERINFO_SUCCESS: 1,
    GET_USERINFO_FAIL: -1,
    GET_OPENID_FAIL: -1
  },
  deps: {
    CREATE_SUCCESS: 1,
    CREATE_FAIL: -1,
    UPDATE_SUCCESS: 1,
    UPDATE_FAIL: -1,
    RETRIEVE_LIST_SUCCESS: 1,
    RETRIEVE_LIST_FAIL: -1,
    DELETE_SUCCESS: 1,
    DELETE_FAIL: -1,
  },
  staff: {
    CREATE_SUCCESS: 1,
    CREATE_FAIL: -1,
    UPDATE_SUCCESS: 1,
    UPDATE_FAIL: -1,
    RETRIEVE_LIST_SUCCESS: 1,
    RETRIEVE_LIST_FAIL: -1,
    DELETE_SUCCESS: 1,
    DELETE_FAIL: -1,
  },
  city: {
    RETRIEVE_STATUS_LIST_SUCCESS: 1,
    RETRIEVE_STATUS_LIST_FAIL: -1,
    CREATE_SUCCESS: 1,
    CREATE_FAIL: -1,
    UPDATE_SUCCESS: 1,
    UPDATE_FAIL: -1,
    RETRIEVE_LIST_SUCCESS: 1,
    RETRIEVE_LIST_FAIL: -1,
    DELETE_SUCCESS: 1,
    DELETE_FAIL: -1,
  },
}
